pluginsGLPI/fields

hook.php
inc/container.class.php
inc/field.class.php
setup.php

Enhancement : Permit to add container for multiples object

Enhancement : Permit to add container for multiples objects

---

inc/container.class.php

Changed way of testing for already defined block for dom insert

---

inc/container.class.php

Fixes retrieving the right container for current type fixes #62

Fixes retrieving the right container for current type fixes #62

---

inc/container.class.php

Added search for container to permit massive update of dropdownuser fields
fixes #25

Added search for container to permit massive update of dropdownuser

---

inc/container.class.php

To check if current object entity matches container entity (+ children)

---

inc/container.class.php

Remove table when class does not exists (should not happen... but...)

---

front/field.form.php
inc/field.class.php

with the merge of #99, the form for field addition fails

fix add new field

---

inc/container.class.php

Limit proposed values in domtab feature to usable ones only

Hardcode domtab possible values

---

inc/profile.class.php

To be able to save profile rights even if it doesn't already exist in DB

To be able to save profile rights even if it not exists in DB

---

.travis.yml
composer.json
composer.lock
setup.php
tests/FieldsDbTestCase.php
tests/bootstrap.php
tests/units/PluginFieldsContainer.php

Update to latest atoum

---

inc/field.class.php
inc/labeltranslation.class.php

See https://github.com/glpi-project/glpi/pull/4384

Removed deprecated usage of Html::scriptStart() and Html::scriptEnd()

---

plugin.xml

Added short and long description as well as language code and tags in Czech language. Sorted alphabetically to correct displaying order on plugins.glpi-project.org
Added proper eclipses, fixed lang markup in tags for French.

l10n – added Czech translation into xml data

---

.travis.yml
hook.php
inc/container.class.php
inc/dropdown.class.php
inc/field.class.php
inc/labeltranslation.class.php
inc/profile.class.php
plugin.xml
setup.php

- Use ITILFollowup in replacement of TicketFollowup
- Use array conditions instead of string in CommonDBTM::find()
- Use array conditions instead of string in Dropdown::show()

GLPI 9.4 compatibility

---

setup.php

Change homepage to github repo

Homepage url

---

inc/toolbox.class.php

Changed \d by [0-9] in regex for mysql, as \d is not POSIX

---

inc/toolbox.class.php

To be sure that query will get only tables from current DB
fixes #321

Added TABLE_SCHEMA = $DB->dbdefault 

---

inc/container.class.php
inc/field.class.php

Required to enable autocomplete on GLPI 9.4.4+ (see https://github.com/glpi-project/glpi/commit/339b856273f2cf5cb409e6db1a2689a418c5a051)

Whitelist autocomplete fields

---

inc/field.class.php

Bug introduce by this commit 
https://github.com/pluginsGLPI/fields/commit/9f5481b8f7e64b679efe72e60001ef45733cfd0e
This  PR fix this
now self service can fill fields with simplified interface.
Best regards

Display field for simplified interface

---

front/field.form.php
inc/field.class.php

fix(core): fix right to purge field

---

front/labeltranslation.form.php
inc/labeltranslation.class.php

Fix rights :
- to create translation
- to purge translations
See #366

fix rights for translations

---

inc/container.class.php

Adds:
- Rack
- Enclosure
- PDU
- Passive DC Equipment
- Certificate
- Data center
- Cluster
- Domain
- Appliance
closes #383
closes #389
closes #392
closes #406
closes #409

Allow fields on DCIM items and a few other types

---

inc/inventory.class.php
setup.php

ADd capabitlity to fields to manage custom fields from fusionInventory

Fusion inventory compatibility

---

inc/container.class.php
inc/field.class.php
inc/migration.class.php

Add operating system  dropdown
bugfixes: When all tabs are displayed, the fields added to the dom are not displayed

add operating system dropdown

---

inc/field.class.php

Fix continue is equivalent to break

---

inc/container.class.php

Displays URL fields correctly in search results

---

inc/field.class.php

Added a test to be sure that $item is entity assigned before using $item->fields['entities_id']

Fix "Undefined index: entities_id" in /fields/inc/field.class.php on line 576"

---

inc/field.class.php

Fix default value in massive actions

---

inc/field.class.php

Default value was never applied

fix: default value was never applied

---

inc/field.class.php
templates/container.class.tpl

Fields deleted in the interface are not deleted in the database
This PR fix this

Fix fields deletion

---

hook.php

as seen from 
https://github.com/pluginsGLPI/fields/pull/472
force regenerate container file when plugin is updated

feat(core): force regenerate container file

---

inc/containerdisplaycondition.class.php

I did not find a case on which value to check would be different from the value  found in `$this->fields`.

Fix container display conditions checks on specific fields

---

inc/container.class.php
inc/field.class.php
inc/migration.class.php
inc/toolbox.class.php
templates/container.class.tpl
templates/fields.html.twig

Add ```itemtype / items_id``` fields

feat(core): add ITEMTYPE / ITEMS_ID field

---

inc/field.class.php

Prevent issues with search options when linking to self

---

inc/container.class.php

Fix: ability to add fields to component

---

inc/containerdisplaycondition.class.php
inc/statusoverride.class.php
templates/container_display_conditions.html.twig

1. Hide button to add a display condition when there are no fields
2. Check that the item type, search option, and condition are set before allowing an add/update
Ref !23913

Check required fields for display conditions

---

templates/forms/status_override.html.twig

Fix field selection in status override edit form

---

inc/container.class.php

Do not check entity on items without entity restrictions

---

inc/field.class.php

Fix PHP error when trying to update data from massive action
Internal ref : !24299

fix(core): prevent error from massive action

---

inc/field.class.php

```dropdownuser``` are never migrated to ```dropdown-User```
Because of typo error/

Fix type migration

---

inc/labeltranslation.class.php

fix(massiveaction): prevent php warning about undefined array key

---

inc/container.class.php

fix check value from mandatory filled field dropdown when use masive action to update fields value.
see !25357

fix(massiveaction): fix check value from dropdown

---

ajax/dropdownDefaultValue.php
ajax/dropdownMultipleDefaultValue.php
front/field.form.php
inc/container.class.php
inc/field.class.php
inc/migration.class.php
templates/container.class.tpl
templates/fields.html.twig

Hello, 
- Implementation of multiple choice dropdowns
- Implementation of default value for dropdowns (single or multiple choice)
- Add default values to the fields defined on a tab other than the main one, during object creation (to be sure that default values will be always present for queries)
Thank you
best regards
Aeto-J

Implementation of multiple choice dropdowns 

---

ajax/field_specific_fields.php

See https://github.com/pluginsGLPI/fields/pull/600#issuecomment-1339024777

Fix default values selection on dropdowns fields

---

inc/toolbox.class.php

To be able to add custom fields to KnowbaseItem class

To be able to add custom fields to KnowbaseItem class

---

inc/container.class.php

Remove use of non-standard SQL `REPLACE INTO` raw query and replace with `DBmysql::updateOrInsert`.

Do not use REPLACE INTO

---

inc/toolbox.class.php

Fix update process.
escape data during field update

fix(core): escape data during field update

---

inc/field.class.php
templates/fields.html.twig

Same as https://github.com/pluginsGLPI/fields/pull/630
but for ```glpi_item``` type field
Internal ref : 28392

fix(core): fix `glpi_item` fields selected value on form refresh/reload

---

inc/container.class.php
inc/field.class.php
inc/migration.class.php
templates/fields.html.twig

Add the possibility to create a richtext field

Added richtext field

---

inc/field.class.php

Clean ```DisplayPreference``` when a field is purge
see !29306

fix(core): clean DisplayPref when field is purged

---

inc/field.class.php
templates/fields.html.twig

On the native self-service ticket creation form, the fields added by the plugin were not aligned with the original fields.
Requires: https://github.com/glpi-project/glpi/pull/15588

fix: field alignment

---

inc/field.class.php

display generic label if not available (to access the field form)
Fix https://github.com/pluginsGLPI/fields/issues/740

Fix(Fields): display generic label if not available

---

inc/containerdisplaycondition.class.php
templates/forms/container_display_condition_so_condition.html.twig

Fix(Condition): load all users from User dropdown

---

CHANGELOG.md
setup.php

- Display generic label for field if not available
- Fix search on dropdown ```multiple```
- Load all users from User dropdown
- Handle / save empty choice for dropdown
- Load overrides from related item if container is ```tab``` type
- Deactivate ```domtab``` that no longer works and handle ```ITILSolution``` (see #741)

1.21.7 bis

---

inc/container.class.php

Adding a solution emptied multiple dropdowns
ref !33268

fix: multiple dropdown fields emptied when solution added

---

CHANGELOG.md
inc/container.class.php

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !33527
After modifying additional fields, the modification date is not updated.

(fix) Update item date_mod

---

css/fields.css
setup.php

fix js/css injection conflict with other plugin (glpiinventory)
`glpiinventory` load ```redips-drag``` only when current page path match ```deploypackage.form.php```
when `fields` always laod same library 
which gives the following error from the `glpiinventory` plugin (when the `fields` plugin is enabled)
<details>
<summary>Browser error</summary>
```shell
VM394:103 JQMIGRATE: Migrate is installed with logging active, version 3.4.0
redips-drag-min.js?v=ed7ede9c291c41b2413350cd12dab099ba6aaa86:62 Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
at Object.init (redips-drag-min.js?v=ed7ede9c291c41b2413350cd12dab099ba6aaa86:62:303)
at redipsInit (drag-field-row.js?v=ed7ede9c291c41b2413350cd12dab099ba6aaa86:39:7)
at <anonymous>:1:1
at x …
```

Fix(Core): fix js/css injection conflict with other plugin

---

.github/workflows/locales-sync.yml
.github/workflows/locales-update-source.yml

Add workflows to sync locales

---

CHANGELOG.md
inc/toolbox.class.php

add ComputerVirtualMachine
see : #824

Feat(core): add ComputerVirtualMachine

---

inc/toolbox.class.php

see https://github.com/glpi-project/glpi/pull/17839
No need to release it now, this change will be mandatory only for GLPI 11.0.

Use dedicated methods to get the list of devices

---

templates/injection.class.tpl

Fix call to get_parent_class() for PHP 8.3

---

CHANGELOG.md
inc/container.class.php

- It fixes !35540
- It fixes the issue that prevented modifying a field via the API when a field and a new tab were added to the same object.

Fix: API issue preventing multi-field updates

---

CHANGELOG.md
inc/container.class.php

- It fixes internal issue (from our inventory)
since https://github.com/pluginsGLPI/fields/pull/911
It is no longer possible to update glpi native fields for bject with `fields` container

Fix(core): revert breaking change

---

front/container.form.php

do no check right when add container

Fix(right): do no check right when add container

---

inc/container.class.php

Better fix for  https://github.com/pluginsGLPI/fields/pull/1009
Fix #1002

Fix(Core): update classname generation method
