pluginsGLPI/fields

- hook.php
Ensure plugin classes are loaded, since GLPi autoloader is disabled for inactive plugins in 0.90
> Fix class loading

- hook.php
The "itemtype" column in containers table doesn't exist anymore, we have to json decode the "itemtypes" column and loop on the result to add each type individually.
> Fixing populate_fields method to handle multiple itemtypes

- inc/field.class.php
Before : when the user had the delete right and no update right on an item type, there was a rendering bug on field type "Insertion in the form (before save
button)"
The condition used on the delete right is useless because the delete right doesn't change the form, while the update right add a Save button.
> bug fix - field render issue depending on rights access

- inc/container.class.php
Container creation form was displaying items that does not have handled tabs when asking for addition of new fields in specific tab.
I refactored the list to filter on the method used to create the handled tab list.
To reproduce:
- create a new block,
- choose "Insertion in the form of a specific tab (before save button)",
- choose "Computer",
- -> tab selection field is not shown
> Fix item types filtering on container form; fixes #269

- inc/migration.class.php
- templates/container.class.tpl
Using API to add fields, we have some messages displayed in the response:
```bash
**$ curl -X POST \
http://localhost/glpi/9.3-git/apirest.php/PluginFieldsField \
-H 'Cache-Control: no-cache' \
-H 'Content-Type: application/json' \
-H 'Session-Token: njf99u23ddkp0qgrpap3podo3h' \
-d ' {"input": {"default_value": "0", "is_active": 1, "label": "test_api", "plugin_fields_containers_id": 10, "type": "text"}}'
<script type='text/javascript'>document.getElementById('').innerHTML="<p class='center'>Changement de la structure de la base de données - glpi_plugin_fields_computertest1s (0 seconde)</p>";</script>
<script type='text/javascript'>document.getElementById('').innerHTML="<p class='center'>Changement de la structure de la base de données - glpi_plugin_fields_tickettest1s (0 …
```
> adding fields display message in innerHtml

- hook.php
- inc/container.class.php
- inc/dropdown.class.php
- inc/field.class.php
- inc/toolbox.class.php
- tests/bootstrap.php
- tests/units/PluginFieldsContainer.php
See https://github.com/glpi-project/glpi/pull/5495
> Generate itemtypes without numbers; fixes #305

- inc/container.class.php
Associated Management/Line to Block #232 
The fields created do not appear in the drop-down menu to select default items to display because a function in hook.php
```
function plugin_fields_getAddSearchOptions($itemtype) {
if (isset($_SESSION['glpiactiveentities'])
&& is_array($_SESSION['glpiactiveentities'])
&& count($_SESSION['glpiactiveentities']) > 0) {
$itemtypes = PluginFieldsContainer::getEntries('all');
if ($itemtypes !== false && in_array($itemtype, $itemtypes)) {
return PluginFieldsContainer::getAddSearchOptions($itemtype);
}
}
return null;
}
```
the php function in_array($itemtype, $itemtypes) return false because $itemtype is in lowercase and the $itemtypes is in upper case.
I think this is caused by an error in the GLPI
> Add fields to Lines

- inc/field.class.php
Fixes #316.
On PHP 7.3, using a continue in a switch is trigerring a warning.
I did not find how (and if) this part of code is used, so I just replace the `continue` by a `break` to keep same behaviour.
> Fix warning: "continue" targeting switch is equivalent to "break"

- .travis.yml
- inc/container.class.php
- inc/field.class.php
Signed-off-by: Stanislas <skita@teclib.com>
Better mangment when item link to container is not assign to entity
Add tab when item is not assign to an entity (entities id not present)
Add dom  when item is not assign to an entity (entities id not present)
Save data when item is not assign to an entity  (entities id not present)
see #347
> fix(core): check if item is entity assign

- .travis.yml
- RoboFile.php
- Add PHP 7.4 in matrix.
- Limit matrix to lowest and highiest PHP supported version.
- Run CS checks in strict mode.
- Remove dead config lines.
> Update Travis configuration

- .travis.yml
- composer.json
- composer.lock
- front/export_to_yaml.php
- inc/container.class.php
- setup.php
Export fields container configuration to YAML file 
ex 
```yaml
container:
2-Peripheral:
id: 2
name: ville
itemtype: Peripheral
fields:
-
id: 11
label: simpletext
xml_node: simpletextfield
type: text
ranking: '1'
default_value: ''
mandatory: '0'
possible_value: ''
-
id: 12
label: yesno
xml_node: yesnofieldtwo
type: yesno
ranking: '2'
default_value: ''
mandatory: '0'
possible_value:
-
id: 0
value: 'No'
-
id: 1
value: 'Yes'
```
export available for all containers
or just one
Signed-off-by: Stanislas <skita@teclib.com>
> Export field conf to yaml file

- inc/container.class.php
- inc/field.class.php
- inc/toolbox.class.php
Add check to prevent usage of field / container name > 64 char after clean by pugin (numeric to string)
Fix migration to prevent usage of table name > 64 char (extract only 64 char if needed) 
see  #344
> Fix numeric name

- inc/field.class.php
Internal ref : !21319.
Extra fields are missing on creation forms if the user's current tab for this itemtype (`$_SESSION['glpi_tabs']`) is not the main one ('$main').
Fix seems to be to add a special case to cover this case like it was done before for the 'showPrimaryForm' and 'showFormHelpdesk' functions.
> Fix extra fields display on creation form

- inc/autoload.php
It seems that in API context, autoload may be called multiple times for the same class. I do not know why, maybe it is related to a call using a wrong case.
Using an `include_once` will not fix the source of this problem, but it cannot hurts and it will prevent the mentionned error.
> Fix multiple includes in API context; fixes #395

- inc/field.class.php
If you add a new fields with a default value, all existing items will display the default values as the current value.
This is incorrect because there is no value in the database (this values will not show up in the search results for example).
To fix this I've limited the code that load the default value to only work on items not saved in the database yet.
!21971
> Do no use default values for existing items

- inc/container.class.php
Fix this notice:
```
PHP Notice: Trying to access array offset on value of type null
```
This is caused by the result of `array_shift($found);` being null.
https://www.php.net/manual/en/function.array-shift.php
> Returns the shifted value, or null if array is empty or is not an array. 
-> the following condition should take into account that the variable may be null.
> Fix php notice when a container is disabled for all profiles

- inc/field.class.php
Instead of locking fields in status "Resolved", they are now still editable but locked in ticket status "Closed" like in all other tabs - look issue #426 and #128
> Allow additionnal field edition on solved tickets; closes #426

- inc/container.class.php
Since release 1.12.1 a bug appears from this PR https://github.com/pluginsGLPI/fields/pull/425
From Dictionnay Software form, it's impossible to add a criteria.
With super-admin profile it's OK 
But with another profile and good right
It's impossible
The "Add" button disappear.
When plugin it's called from this hook
```     
$PLUGIN_HOOKS['post_item_form']['fields'] = ['PluginFieldsField',  'showForTab'];
```
the plugin tries to find a container for the object being viewed (RuleCriteria in this case)
The hook is called from ```CommonDBTM.class.php```
1. Here ```canEdit``` return ```true```
2. Here (after hook) ```can Edit``` return ```false```
When plugin try to find a container related to the object this line break the check process (```canEdit```)
Here we can check directly the arg …
> fix(container): fixing the rights check

- front/commondropdown.form.php
- front/commondropdown.php
If you have a mounted disk, the path check will never succeed because the variables will look like this:
```php
$realpath = /mnt/diskhome/home/...
$frontpath = /home/...
```
It seems like `realpath` should be applied to both path we are trying to compare.
> Fix path check

- front/commondropdown.form.php
- front/commondropdown.php
From CLOUD context ```RuntimeException``` is throw when we try to go to dropdowns created from fields plugin 
```realpath``` =
```/AAA/BBB/CCC/DDD/EEE/glpi_files/_plugins/fields/front/secteurdaffectationfielddropdown.php```
```frontpath``` = 
```/XXX/YYY/CCC/DDD/EEE/glpi_files/_plugins/fields/front```
To prevent load missing or unreadable file just check if it readable or if exist
Internal 23215
> fix(core): better check to include file from path

- inc/field.class.php
Currently when you create a field in a container the plugin automatically adds a translation.
But does not prevent the modification of the field label
This leads to misunderstanding, as users try to change the wording of the field rather than the translation
> fix(UI): prevent name update

- front/regenerate_files.php
- hook.php
- inc/container.class.php
- inc/dropdown.class.php
- setup.php
During install process, all plugin files were dropped, but none were regenerated, as plugin cannot be active when it is not yet installed.
After a quick analysis, I figured out that files were already regenerated by `PluginFieldsContainer::install()` and `PluginFieldsDropdown::install()`, so I removed call to `plugin_fields_checkFiles()` during install process.
I also simplified `plugin_fields_checkFiles()` which is always called with `$force=true` now. Appropriate session/rights checks are done before calling this method, so there is no need to have checks on session inside it.
> Fix files regeneration during install

- hook.php
- inc/container.class.php
- inc/field.class.php
- inc/labeltranslation.class.php
- inc/migration.class.php
- inc/toolbox.class.php
- templates/fields.html.twig
Add new fields
```html
<optgroup label="Modèle" data-select2-id="31">
<option value="dropdowncomputermodels" data-select2-id="32">Modèles d'ordinateurs</option>
<option value="dropdownmonitormodels" data-select2-id="33">Modèles de moniteurs</option>
<option value="dropdownnetworkequipmentmodels" data-select2-id="34">Modèles de matériels réseau</option>
<option value="dropdownperipheralmodels" data-select2-id="35">Modèles de périphériques</option>
<option value="dropdownphonemodels" data-select2-id="36">Modèles de téléphones</option>
<option value="dropdownprintermodels" data-select2-id="37">Modèles d'imprimantes</option>
<option value="dropdownenclosuremodels" data-select2-id="38">Modèles de châssis</option>
<option value="dropdownpdumodels" data-select2-id="39">Modèles de PDU</option> …
```
> feat(fields): add several fields

- inc/statusoverride.class.php
- templates/forms/status_override.html.twig
Default `itemtype` value was containing the translated itemtype, so the status dropdown returned by the `PluginFieldsStatusOverride::getStatusDropdownForItemtype()` method was always corresponding to the default case.
> Fix default itemtype on StatusOverride creation form

- inc/container.class.php
- inc/toolbox.class.php
GLPI 10.0 (2022 version) is not using PDO
> Fix migration of bad named items

- inc/containerdisplaycondition.class.php
On PHP 8.x, `$errcontext` is no more passed to handlers.
> Fix handling of regex display condition

- ajax/viewtranslations.php
- front/containerdisplaycondition.form.php
- front/statusoverride.form.php
- inc/container.class.php
- inc/containerdisplaycondition.class.php
- inc/field.class.php
- inc/labeltranslation.class.php
- inc/profile.class.php
- inc/statusoverride.class.php
> fix: clone container

- inc/field.class.php
See #525 for full details, this function call is broken since 1.15 as the two parameters are inverted.
> Fix field deletion from container table

- templates/fields.html.twig
It is not possible to enforce “Number” type field to be mandatory in GLPIV10 in Fields plugin. This was still possible in V9.5 and stopped working due to changes in V10.
Even when field is marked as mandatory user is never asked to enter or update/fill in the field.
The number field always have default value 0 as this is enforced by core GLPI code in twig macros:
https://github.com/glpi-project/glpi/blob/dccc79cd305e96b272ff12f0b76914ced4b198af/templates/components/form/fields_macros.html.twig#L153
I would like to avoid this and leave number field without any default value so user is enforced to enter it.
If believe this would be probably unacceptable for GLPI team to make it empty for whole GLPI.
So I propose following PR for fields: pass min value so it is empty not 0, if default is not …
> Fix mandatory restriction on Number field type

- inc/migration.class.php
- templates/container.class.tpl
Add default value to prevent SQL error when field ```glpi_item``` is not filled
```sql
[2022-06-08 10:15:16] glpisqllog.ERROR: DBmysql::query() in /home/stanislas/Teclib/dev/GLPI/10.0-bugfixes/src/DBmysql.php line 370
*** MySQL query error:
SQL: INSERT INTO `glpi_plugin_fields_ticketbloc` (`plugin_fields_containers_id`, `items_id`, `plugin_fields_customdropdownfielddropdowns_id`, `nativetextfield`, `nativedatefield`, `nativedatetimefield`, `nativeyesnofield`, `nativeuserfield`) VALUES ('5', '10', '2', 'titi', '2022-06-07', '2022-06-07 10:14:42', '1', '2')
Error: Field 'itemtype_glpiitemfield' doesn't have a default value
Backtrace :
src/DBmysql.php:1312                               
src/CommonDBTM.php:705                             DBmysql->insert()
src/CommonDBTM.php:1297 …
```
> fix(glpi_item): add default value to prevent error when field is not filled

- inc/checkdatabasecommand.class.php
- inc/fixdroppedfieldscommand.class.php
- inc/migration.class.php
Internal ref: !24075.
An issue affected field removal in 1.15.0, 1.15.1 and 1.15.2.
Using these versions, removing a field from a container would drop the field from glpi_plugin_fields_fields but not from the custom container table.
This command remove these incorrectly deleted fields.
Examples:
> Command: fix dropped fields

- inc/container.class.php
With 'tab' type, 
if main itemtype is created from template, tab is display
But this behavior not work ATM
> fix(display): do not display tab from template create form

- inc/container.class.php
Fix #536 , internal ref !24208
@cconard96 what do you think about this fix?
Best regards
> fix(searchoption): search number as text

- ajax/container.php
- ajax/container_display_condition.php
- inc/container.class.php
- inc/containerdisplaycondition.class.php
- inc/field.class.php
- inc/statusoverride.class.php
- templates/fields.html.twig
When self-service select an itil categorie from tick
form is reload and fields don't take care of new value
Only work for itilcategories_id because thatt trigger a reload of form
Fix : (portal) !6633
> fix(display): check data after reload from self-service

- templates/fields.html.twig
fixes #547
1. the wrong variable was evaluated
2. `right: 'all'` should be defined only for `User` dropdown
3. add a `entity_sons: true` to Entity dropdowns
For Entity dropdown, using `entity_sons` seems mandatory, otherwise only one value would be proposed. On other fields, maybe we should add a `recursive` boolean to dropdown in order to giv ability to administrator to define the value to pass to `entity_sons`.
> Fix entity restriction in dropdown

- inc/containerdisplaycondition.class.php
New feature
Add under & not under condition for Tree Dropdown into DisplayCondition
> Add under & not under condition for Tree Dropdown into DisplayCondition

- hook.php
Avoid outputting HTML when running the plugin install though `bin/console` :
```
Traitement du plugin « fields »...
<center><table class='tab_cadre_fixe'><tr><th>Installation des tables MySQL<th></tr><tr class='tab_bg_1'><td align='center'></td></tr></table></center>Le plugin « fields » a été installé et peut être activé.
Traitement du plugin « fields »...
Le plugin « fields » a été activé.
```
> Do not output HTML in command line install

- inc/field.class.php
Seems to be an issue introduced by https://github.com/pluginsGLPI/fields/commit/3dc14345532dcc561528df28fff6c9e7ee8fa15a
I've got some js failure on the computer page:
I've forced loaded tinymce in the relevant function, not sure if it is the best way to fix this.
> Fix tinymce

- inc/container.class.php
Fixes #428 Resolve error "Undefined index: glpiactiveprofile" when using the fields plugin from a cron (automaticAction) job.
> Fix search options generation in CLI context

- templates/fields.html.twig
On a field of type URL, in the link "show" was modified: `&` was replaced by `&#38;` so the link was not valid
ref !25927
> fix: url link was altered

- inc/toolbox.class.php
Base additional fields plugin is missing the ability to add fields to Socket items (formerly network outlet). 
Adding a class reference for Sockets into the getGlpiItemtypes function allows new fields to be added through the plugin.
> Added Sockets to item types

- inc/field.class.php
Fix PHP warning 
```
[2023-02-24 12:14:15] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "multiple" in /var/www/html/glpi/marketplace/fields/inc/field.class.php at line 1101
Backtrace :
marketplace/fields/inc/field.class.php:1164        PluginFieldsField::prepareHtmlFields()
marketplace/fields/hook.php:207                    PluginFieldsField::showSingle()
src/Plugin.php:1610                                plugin_fields_MassiveActionsFieldsDisplay()
src/MassiveAction.php:1176                         Plugin::doOneHook()
src/MassiveAction.php:908                          MassiveAction::showMassiveActionsSubForm()
ajax/dropdownMassiveAction.php:53                  MassiveAction->showSubForm()
```
Internal ref : !26921
> fix(massiveaction): fix undefined index 'mutliple'

- inc/field.class.php
Do not refresh tab container when form is reload (when ```itilcategories_id``` change)
to prevent twice call 
The first one ( ```itilcategories_id``` change) get right value but unset it from ```$_SESSION``` 
The second call (caused by reload page) return ```NULL```
When field refresh container (to check visibility) data are not set in ```$_SESSION```  but in ```$item->input```
TRy to find value from ```$_SESSION``` first then in ```$item->input```
Internal ref = !26275
> fix(core): fix found value on refresh

- inc/field.class.php
For yesno field default value must be 0
If default value is not set and readonly is active that create an sql error :
Error: Incorrect integer value: '' for column 'fieldname' at row 1
> Fix yes/no default value

- inc/containerdisplaycondition.class.php
Change id of location in allowed_so: id 80 is Entity and 83 is Location
replace id 80 by 83
and we use $array (searchoptions) like others datatype
> Change location id in allowed_so

- inc/container.class.php
Context : password update (from policies) and container added to ```User```
During password update process 
```$_SESSION['glpiactiveprofile']['id']```  is isset but with ```null``` value.
PHP ```Fatal error``` is triggered
This PR fix this.
Fix : !29262
> fix(core): prevent error when check contaier rights

- inc/field.class.php
Replaces #691.
The `PluginFieldsToolbox::fixFieldsNames()` is required for migrations from version <= 1.9.2 (see #306).
> Fix fields naming conflict checks

- inc/container.class.php
Usage of dynamic properties is deprecated since PHP 8.2.
> Remove usage of deprecated dynamic properties

- inc/container.class.php
Default value for $id must be false, otherwise the searches for container in preItem() will failed.
> Fix issue with wrong default value for container

- inc/container.class.php
Fixes following errors:
```
[2023-09-14 10:50:57] glpiphplog.WARNING: *** PHP Warning (2): Undefined variable $updates in C:\inetpub\wwwroot\marketplace\fields\inc\container.class.php at line 1330
Backtrace :
marketplace\fields\inc\container.class.php:1195 PluginFieldsContainer::constructHistory()
marketplace\fields\inc\container.class.php:1595 PluginFieldsContainer->updateFieldsValues()
src\Plugin.php:1475 PluginFieldsContainer::preItemUpdate()
src\CommonDBTM.php:1591 Plugin::doHook()
front\ticket.form.php:84 CommonDBTM->update()
[2023-09-14 10:50:57] glpiphplog.WARNING: *** PHP Warning (2): foreach() argument must be of type array|object, null given in C:\inetpub\wwwroot\marketplace\fields\inc\container.class.php at line 1330
Backtrace :
marketplace\fields\inc\container.class.php:1195 …
```
> Fix error when no fields are updated

- setup.php
For example, when a text input was added to a ticket and `\` were entered, these were interpreted when the ticket was reloaded by the save action, but not when the ticket was simply loaded.
Original value:
Before fix:
> fix: backslash in input text

- .github/workflows/continuous-integration.yml
I made a reusable workflow that we could use in all ours plugins in order to simplify the way they are configured in each plugin.
See https://github.com/glpi-project/plugin-ci-action/blob/main/.github/workflows/continuous-integration.yml
> Run tests using `glpi-project/plugin-ci-action` workflow

- hook.php
- inc/abstractcontainerinstance.class.php
- inc/container.class.php
Fix search on multiple dropdown
Actually, ```multiple dropdown``` only use ```contain``` / ```not contain``` ```searchtype```.
SQL query is computed with ```=``` on column that contain ```['ID', 'ID, 'ID']``` and try to match ```string```
Use of ```plugin_fields_addWhere``` to replace ```=``` by ```like``` when related field is from plugin ```fields``` and when it's ```multiple```
Use of ```getSpecificValueToSelect``` to display a ```real``` dropdown.
Force ```'equals', 'notequals'``` ```searchtype```
Fix : internal ref 31426
> fix(SearchOption): Fix search on multiple dropdown

- inc/container.class.php
If the user empties a multi drop-down list and saves
the choice is not saved
fix : https://github.com/pluginsGLPI/fields/issues/728
> fix(Multi Dropdown): handle / save empty choice

- inc/container.class.php
- templates/status_overrides.html.twig
Container with 'tab' type can load override 
it does not contain the fields of the parent object in $data
This PR fix this by loading overrides with related item fields instead of $data
Fix : https://github.com/pluginsGLPI/fields/issues/739
Add explanatory text
Fix : https://github.com/pluginsGLPI/fields/issues/738
> Fix(Overrides): load overrides from related item if container is 'tab' type

- CHANGELOG.md
- inc/container.class.php
Prevent PHP warning / error
```shell
PHP Warning (2): Undefined array key "itemtype" in /mnt/diskhome/home/osu7snko7a9h/dbn41swHoff/htdocs/marketplace/fields/inc/container.class.php at line 1444
Uncaught Exception Error: Class name must be a valid object or a string in /mnt/diskhome/home/osu7snko7a9h/dbn41swHoff/htdocs/marketplace/fields/inc/container.class.php at line 1444
```
Fix #764
> Fix(Container): fix undefined array key

- templates/fields.html.twig
When the item is on a recursive entity, the dropdown added by fields didn't propose any values in the child entities.
Example: a network port, where Fields adds a port field (to link this port to another). Although the port is recursive, the dropdown did not list the ports of the child entities.
ref !31937
> fix dropdown recursion

- inc/containerdisplaycondition.class.php
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !32319
The list of fields available for adding conditions to plugins fields was incomplete.
Many fields linked to an item were not displayed in the list (e.g. ApplianceType for Appliances).
This fix adds them.
> Fix list of allowed Search Option

- setup.php
```load``` / ```enable``` plugin from CLI
should fix : https://github.com/glpi-project/glpi-inventory-plugin/issues/492
```SearchOption``` errors from ```fields``` when a ```CLI``` task executes a command using the fields
> Fix(core): load plugin from CLI

- templates/injection.class.tpl
Prevent this error message:
```
glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: get_parent_class(): Argument #1 ($object_or_class) must be an object or a valid class name, null given in /var/www/glpi/files/_plugins/fields/inc/computerchampsadditionnelordinateurinjection.class.php at line 15
Backtrace :
...ampsadditionnelordinateurinjection.class.php:15 get_parent_class()
...e/datainjection/inc/injectiontype.class.php:147 PluginFieldsComputerchampsadditionnelordinateurInjection::getTable()
...etplace/datainjection/inc/mapping.class.php:145 PluginDatainjectionInjectionType::dropdownLinkedTypes()
marketplace/datainjection/inc/model.class.php:843  PluginDatainjectionMapping::showFormMappings()
src/CommonGLPI.php:694 …
```
> fix: Prevent error when classname is null

- CHANGELOG.md
- inc/container.class.php
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !33520
When filling in a RichText field for the first time, an error appears on the screen.
This is due to the attempt to save data in the _updater_... parameter, which is an array, causing the error.
> (fix) Strpslashes log error

- CHANGELOG.md
- templates/injection.class.tpl
revert https://github.com/pluginsGLPI/fields/pull/798
Just ```getTableForItemType``` with ```get_parent_class()``` (without pass ```$classname``` as parameter because is always ```NULL```)
fix : !33438 and !33460 and !33597
> Fix(Injection): fix datainjection error with fields

- CHANGELOG.md
- inc/container.class.php
Related ticket : 33594
Plugins : **Generic Objects** X **Fields**
For a generic `Car` object, for example, if you add multiple mandatory fields pointing to GLPI objects (Dropdowns Groups, Users, etc.), object creation fails with an error indicating that mandatory fields are empty.
What's more, once this problem had been resolved, it was possible to enter empty values in mandatory fields, because in some cases, if the field in question was not detected in the code (in the case of an empty value) the value was retrieved from the database to check that a mandatory field was indeed non-empty. This meant that an empty value could only be entered in a mandatory field once (which is already too often).
> Fix mandatory dropdown fields

- CHANGELOG.md
- inc/field.class.php
In fields, a dropdown field can be reused in several containers
However, when several containers use this type of field, it is no longer possible to modify it using mass actions.
The format of the query before the change resulted in an `IN` clause which returned both containers (KO), now we have a `LIKE` clause (which returns a single container (OK)).
> Fix(Core): fix bulk update for dropdown used in more than one container

- ajax/field_specific_fields.php
- It fixes !34700
The core does not support handling multiple documents in a single field, so this PR proposes to simply remove the option.
> fix: remove multiple dropdown option for documents

- inc/container.class.php
- inc/field.class.php
- It fixes !34825
You can define the tag/label of a field in the fields plugin, but when it is modified it is not updated on the pages and keeps the first name that was defined for it.
> Fix field Tab Display label

- setup.php
- It fixes #860
This PR adjusts the file regeneration process created by `fields`. 
From now on, the files will be generated in two steps:
- Generation of files related to dropdowns.
- Generation of files related to containers.
This prevents a fatal error when a `container` is added to a `dropdown` created in another `container` (and not yet generated).
> Fix(Generate): generate Dropdown before container

- CHANGELOG.md
- inc/abstractcontainerinstance.class.php
- setup.php
- templates/container.class.tpl
This PR corrects a behaviour identified in the `fields` plugin. Until now, when calling the API to retrieve one or more containers (`https://<FQDN>/apirest.php/PluginFields<BlockName>`), the plugin did not correctly check the associated access rights and return all data.
This update introduces a systematic rights check for each container retrieved.
Before checl : 
```shell
curl -X GET \
-H 'Content-Type: application/json' \
-H "Session-Token: qcs67di01ckfifaktuenldsu3c" \
-H "App-Token: OtWWECjVh4XjCXtxb0qU1yNF9cA3E5xtl8BOMuHx" \
'http://glpi10bf.local/apirest.php/PluginFieldsTickettest/1?expand_dropdowns=true'
{"id":1,"items_id":"Related ticket","itemtype":"Ticket","plugin_fields_containers_id":"test","texttestfield":"test","links":[{"rel":"T …
```
> Fix(Core): Add entities_id and is_recursive fields to correctly filter data from the API

- CHANGELOG.md
- inc/field.class.php
- It fixes !35567
If two blocks share the same dropdown field, removing it from the first block disrupts the second, as the associated dropdown table/class is deleted while still being referenced elsewhere.
This PR introduces a verification step before deleting a field, ensuring it is not in use by another block, thus preventing data inconsistencies and operational issues.
> Prevent destroy

- CHANGELOG.md
- inc/container.class.php
- It fixes !35167
- Change the decimal type of number fields to display the decimal part of the decimal numbers in search options
> fix: datatype number for search

- CHANGELOG.md
- inc/container.class.php
- It fixes
- #882 
- #881 
- #888 
- Alternative for https://github.com/pluginsGLPI/fields/pull/892
> revert: fix(875): allow multi update from API

- CHANGELOG.md
- inc/containerdisplaycondition.class.php
- It fixes #900 
An error occurs during display when a `PluginFieldsContainerDisplayCondition` is associated with a dropdown that is no longer available (e.g., deleted).
This PR fix this
> Fix(Condition): Fix display when value is no more available

- CHANGELOG.md
- inc/container.class.php
- It fixes #835
From `API`, plugin need to check from `$item->input` to get related container instead of check `$_REQUEST` whioch is not relevant from `API` process
> Fix api container tab update

- CHANGELOG.md
- ajax/field_specific_fields.php
- It fixes #36030
- When creating a dropdown, no default value was defined. In the database, the default value was "NULL" which caused some problems such as not checking the mandatory fields.
> fix: add default value for dropdown to avoid empty dropdown

- CHANGELOG.md
- inc/container.class.php
Unable to update fields from Formcreator plugin (which add `c_id` to input)
So rely on input first (see with Formcreator plugin)
> Fix(fields): rely on input first

- inc/container.class.php
- It fixes N/A
Hide fields 'tab' from template as it's content is not display
Like 
```php
public static function displayTabContentForItem(CommonGLPI $item, $tabnum = 1, $withtemplate = 0)
{
if ($withtemplate) {
//Do not display tab from template or from item created from template
return false;
}
```
but for 
```public function getTabNameForItem(CommonGLPI $item, $withtemplate = 0)```
> Fix(core): Hide fields 'tab' from template as it's content is not display

- CHANGELOG.md
- hook.php
- inc/container.class.php
- It fixes !36664
Fix the ability to search on 'number' fields 
**Before :**
**After :**
> Fix number search option

- CHANGELOG.md
- inc/container.class.php
- It fixes !36465
When a container is defined as type `dom` (displayed before the save button), the data entry process differs from that in `tab` mode. It is necessary to manually add the `entities_id` to ensure it is recorded in the container's table
> Fix(Container): save entites_id manually from container type 'dom'

- CHANGELOG.md
- inc/container.class.php
- It fixes !37010
If a required multiple dropdown field is present in our ticket form, it is currently possible to create a ticket without selecting any values.
The issue comes from the validation function, which only checks if a required field is empty but does not properly handle multiple-selection fields. For a standard dropdown, the function considers a value of 0 as empty. However, for a multiple dropdown, an unselected field results in an empty array, which is not detected as invalid.
A specific condition must be added to check if a required multiple-selection field is empty by detecting empty arrays during validation.
> Fix - Validation for mandatory multiple dropdown

- CHANGELOG.md
- inc/field.class.php
- It fixes #947
Prevent duplicate call only from new object
> Fic(Condition): Fix condition check logic for dropdown field values

- CHANGELOG.md
- inc/container.class.php
- It fixes !38252
- Massive actions did not work on the multiple fields of the field plugin
> fix(MassiveAction): fix incompatibility with multiple dropdowns

- CHANGELOG.md
- inc/container.class.php
- It fixes 
When importing with DataInjection, for example, an error occurs: Undefined array key ‘multiple_dropdown_action’
> Add isset an `multiple_dropdown_action`

- CHANGELOG.md
- hook.php
- inc/dropdown.class.php
- It fixes !39008
The “is not” search on a multiple dropdown field was not working.
> Fix: search on multi-dropdown

- CHANGELOG.md
- inc/container.class.php
- It fixes !38850
Correction of the bulk action to add value to multiple drop-down fields, specifically the ‘Add’ option, which now compares the values in the table rather than the keys in order to prevent duplicates.
> Fix massive action add multiple dropdown
